version: "3.12"

services:
  app:
    container_name: mangabot
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
